#!/bin/bash

# List all available MCP tools

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                                                               ║"
echo "║     📋 Notion MCP Server - Available Tools                   ║"
echo "║                                                               ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ Available Tools (8 total):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📄 Page Operations:"
echo "  1. create_page      - Create a new page (record) in a database"
echo "  2. get_page         - Retrieve a specific page by ID"
echo "  3. update_page      - Update page properties (ALL types supported)"
echo "  4. delete_page      - Delete (archive) a page"
echo "  5. query_pages      - Query/filter/sort pages in a database"
echo ""
echo "🗄️  Database Operations:"
echo "  6. get_database     - Get database details and schema"
echo "  7. list_databases   - List all accessible databases"
echo "  8. update_database  - Update database settings"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔍 Key Features:"
echo "  ✅ Query pages with filters and sorting"
echo "  ✅ Update ANY property type (12+ types)"
echo "  ✅ Multiple property updates in single call"
echo "  ✅ Full CRUD operations"
echo ""
echo "📖 For detailed usage, see:"
echo "  • README.md"
echo "  • PROPERTY_UPDATE_GUIDE.md"
echo "  • EXAMPLES.md"
echo ""

